# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad08a9b00d18bf7a3afe90d3504eff9b78a7741017b71c612f2094ccf21cc67b87e95cd9e8459d1ddf4f0cdc0994e2487cc27e0efa3aff4c1bfc850d4a89254c

test:
  secret_key_base: 8406052cfa8338c8b571f530b6722a40deeb289f1c80224645c353e4d57eac175f466e567cd0d443b52721fdad2cbd45037ead3ba712b7f85ab2efe90b5d0303

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
